#!/bin/bash

# test_psn_matlab_python_equivalence.sh
#
# This script tests numeric equivalence between Python and MATLAB implementations
# of PSN using simulated data generated by simulate_data.py.
#
# Usage:
#   ./test_psn_matlab_python_equivalence.sh [test_number]
#
# Arguments:
#   test_number - Optional. Run only a specific test (1-10), or "all" (default)
#
# Examples:
#   ./test_psn_matlab_python_equivalence.sh        # Run all tests
#   ./test_psn_matlab_python_equivalence.sh all    # Run all tests
#   ./test_psn_matlab_python_equivalence.sh 5      # Run only test 5
#   ./test_psn_matlab_python_equivalence.sh 1      # Run only test 1
#
# IMPORTANT: MATLAB is considered the ground truth implementation.
# If discrepancies are found, the Python implementation should be modified
# to match MATLAB, not the other way around.
#
# REPRODUCIBILITY: Both Python and MATLAB implementations use random_seed=42
# to ensure deterministic results for perfect cross-platform equivalence testing.

set -e  # Exit on any error

# Parse command-line arguments
TEST_TO_RUN="${1:-all}"

if [[ "$TEST_TO_RUN" != "all" ]] && ! [[ "$TEST_TO_RUN" =~ ^[1-9]$|^10$ ]]; then
    echo "Error: Invalid test number '$TEST_TO_RUN'. Must be 1-10 or 'all'"
    echo "Usage: $0 [test_number|all]"
    exit 1
fi

# ==================== CONFIGURATION ====================
# MATLAB configuration
MATLAB_PATH="/Applications/MATLAB_R2022b.app/bin/matlab"

# Python configuration
PYTHON_CMD="python3"

# Test configuration
TOLERANCE="1e-10"  # High precision tolerance for equivalence testing with deterministic random seeds
MIN_CORRELATION="0.999999"  # Very high correlation threshold for deterministic equivalence
# ========================================================

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PSN_ROOT="$(dirname "$SCRIPT_DIR")"  # Parent directory since script is in tests/
PYTHON_DIR="$PSN_ROOT/psn"
MATLAB_DIR="$PSN_ROOT/matlab"
TEST_DATA_DIR="$SCRIPT_DIR/psn_equivalence_test_data"

# Create test data directory
mkdir -p "$TEST_DATA_DIR"

echo "=========================================="
echo "PSN Python-MATLAB Equivalence Test"
echo "=========================================="
echo "Test data directory: $TEST_DATA_DIR"
echo "Tolerance: $TOLERANCE"
echo "Min correlation: $MIN_CORRELATION"
echo ""

# Check if MATLAB is available
if [ ! -f "$MATLAB_PATH" ]; then
    echo "MATLAB not found at $MATLAB_PATH"
    echo "Please update the MATLAB_PATH variable in this script or ensure MATLAB is in PATH"
    # Try fallback to system matlab
    if ! command -v matlab &> /dev/null; then
        echo "ERROR: MATLAB not found. Please ensure MATLAB is installed."
        exit 1
    else
        MATLAB_PATH="matlab"
        echo "Using system MATLAB from PATH"
    fi
fi

# Check if Python and required packages are available
if ! $PYTHON_CMD -c "import numpy, scipy, sys; sys.path.insert(0, '$PSN_ROOT'); from psn.psn import psn" &> /dev/null; then
    echo "ERROR: Python or required packages not available. Please check installation."
    echo "Tried to use: $PYTHON_CMD"
    echo "Required packages: numpy, scipy"
    exit 1
fi

echo "Environment checks passed."
echo ""

# Function to check if a test should run based on command-line argument
should_run_test() {
    local test_num="$1"
    if [[ "$TEST_TO_RUN" == "all" ]] || [[ "$TEST_TO_RUN" == "$test_num" ]]; then
        return 0
    else
        return 1
    fi
}

# Function to generate test data and run PSN equivalence test
run_psn_equivalence_test() {
    local test_name="$1"
    local nvox="$2"
    local ncond="$3"
    local ntrial="$4"
    local basis="$5"
    local criterion="$6"
    local threshold_method="$7"
    local variance_threshold="${8:-0.99}"

    echo "=========================================="
    echo "Testing: $test_name"
    echo "Parameters: $nvox voxels, $ncond conditions, $ntrial trials"
    echo "basis=$basis, criterion=$criterion, threshold_method=$threshold_method"
    echo "variance_threshold=$variance_threshold"
    echo "=========================================="

    # Generate test data with Python
    cat > "$TEST_DATA_DIR/generate_${test_name}_data.py" << 'EOFPYTHON'
import numpy as np
import scipy.io
import sys
import os

# Add PSN to path
sys.path.insert(0, 'PSN_ROOT_PLACEHOLDER')
from psn.utilities.simulation.simulate_data import generate_data

# Set random seed for reproducibility
np.random.seed(42)

# Generate simulated data
print("Generating simulated data...")
print(f"Shape: {NVOX_PLACEHOLDER} voxels × {NCOND_PLACEHOLDER} conditions × {NTRIAL_PLACEHOLDER} trials")

train_data, test_data, ground_truth = generate_data(
    nvox=NVOX_PLACEHOLDER,
    ncond=NCOND_PLACEHOLDER,
    ntrial=NTRIAL_PLACEHOLDER,
    signal_decay=1.0,
    noise_decay=1.0,
    noise_multiplier=1.0,
    align_alpha=0.5,
    align_k=min(5, NVOX_PLACEHOLDER//2),
    random_seed=42,
    want_fig=False,
    verbose=False
)

print(f"Generated data shape: {train_data.shape}")
print(f"Data range: [{np.min(train_data):.6f}, {np.max(train_data):.6f}]")
print(f"Data mean: {np.mean(train_data):.6f}")
print(f"Data std: {np.std(train_data):.6f}")

# Check for NaN or inf values
if not np.isfinite(train_data).all():
    raise ValueError("Generated data contains NaN or Inf values")

# Save data for both Python and MATLAB
np.save('TEST_DATA_DIR_PLACEHOLDER/TEST_NAME_PLACEHOLDER_data.npy', train_data)
scipy.io.savemat('TEST_DATA_DIR_PLACEHOLDER/TEST_NAME_PLACEHOLDER_data.mat', {'data': train_data})

print("Test data generated and saved successfully")
EOFPYTHON

    # Replace placeholders in Python script
    sed "s|PSN_ROOT_PLACEHOLDER|$PSN_ROOT|g; s|TEST_DATA_DIR_PLACEHOLDER|$TEST_DATA_DIR|g; s|TEST_NAME_PLACEHOLDER|$test_name|g; s|NVOX_PLACEHOLDER|$nvox|g; s|NCOND_PLACEHOLDER|$ncond|g; s|NTRIAL_PLACEHOLDER|$ntrial|g" \
        "$TEST_DATA_DIR/generate_${test_name}_data.py" > "$TEST_DATA_DIR/generate_${test_name}_data_tmp.py"
    mv "$TEST_DATA_DIR/generate_${test_name}_data_tmp.py" "$TEST_DATA_DIR/generate_${test_name}_data.py"

    $PYTHON_CMD "$TEST_DATA_DIR/generate_${test_name}_data.py"

    # Run Python PSN
    cat > "$TEST_DATA_DIR/run_python_${test_name}.py" << 'EOFPYTHON'
import numpy as np
import scipy.io
import sys
import os
import time

# Add PSN to path
sys.path.insert(0, 'PSN_ROOT_PLACEHOLDER')
from psn.psn import psn

# Set random seed for reproducibility
np.random.seed(42)

# Load data
data = np.load('TEST_DATA_DIR_PLACEHOLDER/TEST_NAME_PLACEHOLDER_data.npy')
print(f"Running Python PSN on TEST_NAME_PLACEHOLDER data...")
print(f"Data shape: {data.shape}")

# Special handling for custom basis test
if "BASIS_PLACEHOLDER" == "shared_random_basis":
    # Load shared random basis
    shared_basis = np.load('TEST_DATA_DIR_PLACEHOLDER/shared_random_basis.npy')
    print(f"Loaded shared random basis with shape: {shared_basis.shape}")
    basis_param = shared_basis
else:
    basis_param = "BASIS_PLACEHOLDER"

# Set options
opt = {
    'basis': basis_param,
    'criterion': 'CRITERION_PLACEHOLDER',
    'threshold_method': 'THRESHOLD_METHOD_PLACEHOLDER',
    'variance_threshold': VARIANCE_THRESHOLD_PLACEHOLDER,
    'wantfig': False,
    'wantverbose': False
}

# Run PSN with timing
start_time = time.time()
results = psn(data, opt)
end_time = time.time()

print(f"Python computation completed in {end_time - start_time:.2f} seconds")

# Save results (exclude non-serializable items)
serializable_results = {}
for key, value in results.items():
    if not callable(value) and key != 'opt_used':  # Exclude function handles and opt dict
        serializable_results[key] = value

np.save('TEST_DATA_DIR_PLACEHOLDER/TEST_NAME_PLACEHOLDER_python_results.npy', serializable_results)

# Convert numpy arrays to MATLAB-compatible format for comparison
matlab_results = {}
for key, value in serializable_results.items():
    if isinstance(value, np.ndarray):
        matlab_results[key] = value
    elif isinstance(value, (int, float, np.integer, np.floating)):
        matlab_results[key] = np.array([[value]])  # Scalar as 1x1 matrix
    elif isinstance(value, dict):
        # Skip nested dictionaries
        print(f"Warning: Skipping dictionary field {key} for MATLAB comparison")
        continue
    elif value is not None:
        try:
            matlab_results[key] = np.array(value)
        except:
            print(f"Warning: Could not convert {key} to MATLAB format")

scipy.io.savemat('TEST_DATA_DIR_PLACEHOLDER/TEST_NAME_PLACEHOLDER_python_results.mat', matlab_results)

# Print key results info
print(f"Results summary:")
print(f"Available fields: {list(serializable_results.keys())}")
if 'denoiser' in serializable_results and serializable_results['denoiser'] is not None:
    print(f"  denoiser shape: {serializable_results['denoiser'].shape}")
if 'denoiseddata' in serializable_results and serializable_results['denoiseddata'] is not None:
    print(f"  denoiseddata shape: {serializable_results['denoiseddata'].shape}")
if 'best_threshold' in serializable_results and serializable_results['best_threshold'] is not None:
    if np.isscalar(serializable_results['best_threshold']):
        print(f"  best_threshold: {serializable_results['best_threshold']}")
    else:
        print(f"  best_threshold shape: {serializable_results['best_threshold'].shape}")
        print(f"  best_threshold range: [{np.min(serializable_results['best_threshold'])}, {np.max(serializable_results['best_threshold'])}]")

print("Python results saved successfully")
EOFPYTHON

    # Replace placeholders
    sed "s|PSN_ROOT_PLACEHOLDER|$PSN_ROOT|g; s|TEST_DATA_DIR_PLACEHOLDER|$TEST_DATA_DIR|g; s|TEST_NAME_PLACEHOLDER|$test_name|g; s|BASIS_PLACEHOLDER|$basis|g; s|CRITERION_PLACEHOLDER|$criterion|g; s|THRESHOLD_METHOD_PLACEHOLDER|$threshold_method|g; s|VARIANCE_THRESHOLD_PLACEHOLDER|$variance_threshold|g" \
        "$TEST_DATA_DIR/run_python_${test_name}.py" > "$TEST_DATA_DIR/run_python_${test_name}_tmp.py"
    mv "$TEST_DATA_DIR/run_python_${test_name}_tmp.py" "$TEST_DATA_DIR/run_python_${test_name}.py"

    $PYTHON_CMD "$TEST_DATA_DIR/run_python_${test_name}.py"

    # Run MATLAB PSN
    cat > "$TEST_DATA_DIR/run_matlab_${test_name}.m" << 'EOFMATLAB'
try
    % Add PSN matlab directory and all subdirectories to path
    addpath(genpath('MATLAB_DIR_PLACEHOLDER'));

    % Set random seed for reproducibility
    rng('default');
    rng(42, 'twister');

    % Load data
    load('TEST_DATA_DIR_PLACEHOLDER/TEST_NAME_PLACEHOLDER_data.mat');
    fprintf('Running MATLAB PSN on TEST_NAME_PLACEHOLDER data...\n');
    fprintf('Data shape: [%d, %d, %d]\n', size(data));

    % Special handling for custom basis test
    if strcmp('BASIS_PLACEHOLDER', 'shared_random_basis')
        % Load shared random basis
        shared_basis_data = load('TEST_DATA_DIR_PLACEHOLDER/shared_random_basis.mat');
        shared_basis = shared_basis_data.shared_basis;
        fprintf('Loaded shared random basis with shape: [%d, %d]\n', size(shared_basis));
        basis_param = shared_basis;
    else
        basis_param = 'BASIS_PLACEHOLDER';
    end

    % Set options
    opt = struct();
    opt.basis = basis_param;
    opt.criterion = 'CRITERION_PLACEHOLDER';
    opt.threshold_method = 'THRESHOLD_METHOD_PLACEHOLDER';
    opt.variance_threshold = VARIANCE_THRESHOLD_PLACEHOLDER;
    opt.wantfig = 0;
    opt.wantverbose = 0;

    % Run PSN with timing
    tic;
    results = psn(data, opt);
    elapsed = toc;

    fprintf('MATLAB computation completed in %.2f seconds\n', elapsed);

    % Save results
    save('TEST_DATA_DIR_PLACEHOLDER/TEST_NAME_PLACEHOLDER_matlab_results.mat', '-struct', 'results');

    % Print key results info
    fprintf('Results summary:\n');
    if isfield(results, 'denoiser') && ~isempty(results.denoiser)
        fprintf('  denoiser shape: [%d, %d]\n', size(results.denoiser));
    end
    if isfield(results, 'denoiseddata') && ~isempty(results.denoiseddata)
        fprintf('  denoiseddata shape: [%s]\n', num2str(size(results.denoiseddata)));
    end
    if isfield(results, 'best_threshold') && ~isempty(results.best_threshold)
        if isscalar(results.best_threshold)
            fprintf('  best_threshold: %d\n', results.best_threshold);
        else
            fprintf('  best_threshold shape: [%s]\n', num2str(size(results.best_threshold)));
            fprintf('  best_threshold range: [%d, %d]\n', min(results.best_threshold), max(results.best_threshold));
        end
    end

    fprintf('MATLAB results saved successfully\n');

    % Success
    exit(0);
catch ME
    fprintf('Error in MATLAB PSN:\n');
    fprintf('Message: %s\n', ME.message);
    fprintf('Identifier: %s\n', ME.identifier);
    for i = 1:length(ME.stack)
        fprintf('  File: %s, Function: %s, Line: %d\n', ...
                ME.stack(i).file, ME.stack(i).name, ME.stack(i).line);
    end
    exit(1);
end
EOFMATLAB

    # Replace placeholders in MATLAB script
    sed "s|MATLAB_DIR_PLACEHOLDER|$MATLAB_DIR|g; s|TEST_DATA_DIR_PLACEHOLDER|$TEST_DATA_DIR|g; s|TEST_NAME_PLACEHOLDER|$test_name|g; s|BASIS_PLACEHOLDER|$basis|g; s|CRITERION_PLACEHOLDER|$criterion|g; s|THRESHOLD_METHOD_PLACEHOLDER|$threshold_method|g; s|VARIANCE_THRESHOLD_PLACEHOLDER|$variance_threshold|g" \
        "$TEST_DATA_DIR/run_matlab_${test_name}.m" > "$TEST_DATA_DIR/run_matlab_${test_name}_tmp.m"
    mv "$TEST_DATA_DIR/run_matlab_${test_name}_tmp.m" "$TEST_DATA_DIR/run_matlab_${test_name}.m"

    "$MATLAB_PATH" -nosplash -nodesktop -r "try; run('$TEST_DATA_DIR/run_matlab_${test_name}.m'); catch ME; disp('Error running MATLAB:'); disp(ME.message); disp(ME.stack); exit(1); end"

    # Compare results
    cat > "$TEST_DATA_DIR/compare_${test_name}.py" << 'EOFPYTHON'
import numpy as np
import scipy.io
import sys

# Load both results directly from .mat files
python_results = scipy.io.loadmat('TEST_DATA_DIR_PLACEHOLDER/TEST_NAME_PLACEHOLDER_python_results.mat')
matlab_results = scipy.io.loadmat('TEST_DATA_DIR_PLACEHOLDER/TEST_NAME_PLACEHOLDER_matlab_results.mat')

# Filter out MATLAB internal fields
matlab_internal_fields = ['__header__', '__version__', '__globals__']
for field in matlab_internal_fields:
    python_results.pop(field, None)
    matlab_results.pop(field, None)

# Print available fields for debugging
print(f"Python result fields: {sorted(python_results.keys())}")
print(f"MATLAB result fields: {sorted(matlab_results.keys())}")
print("")

tolerance = TOLERANCE_PLACEHOLDER
min_correlation = MIN_CORRELATION_PLACEHOLDER

max_error = 0.0
failed_fields = []
correlation_failed_fields = []

# Fields to compare - focusing on the core PSN outputs
fields_to_compare = ['denoiser', 'denoiseddata', 'best_threshold', 'fullbasis']

# Add optional fields that may be present depending on parameters
optional_fields = ['signalvar', 'noisevar', 'objective', 'signalsubspace', 'dimreduce',
                   'basis_eigenvalues', 'unitreorderings', 'svnv_before', 'svnv_after']
for field in optional_fields:
    if field in python_results and python_results[field] is not None:
        if field in matlab_results:
            fields_to_compare.append(field)

print("=" * 60)
print(f"COMPARING PYTHON vs MATLAB RESULTS FOR TEST_NAME_PLACEHOLDER")
print("=" * 60)
print(f"Tolerance: {tolerance}")
print(f"Minimum correlation: {min_correlation}")
print("")

for field in fields_to_compare:
    if field in python_results and python_results[field] is not None and field in matlab_results:
        py_val = python_results[field]
        mat_val = matlab_results[field]

        # Handle MATLAB's and Python's tendency to add extra dimensions to scalars
        if hasattr(mat_val, 'squeeze'):
            mat_val = mat_val.squeeze()
        if hasattr(py_val, 'squeeze'):
            py_val = py_val.squeeze()

        # Convert Python scalars to numpy arrays for consistent handling
        if np.isscalar(py_val):
            py_val = np.array(py_val)
        if np.isscalar(mat_val):
            mat_val = np.array(mat_val)

        # Handle potential shape differences (MATLAB vs Python conventions)
        if py_val.shape != mat_val.shape:
            # Try transpose if shapes are swapped
            if len(py_val.shape) == len(mat_val.shape) and py_val.shape == mat_val.T.shape:
                mat_val = mat_val.T
                print(f"NOTE: {field} - Transposed MATLAB result to match Python shape")
            else:
                print(f"FAIL: {field} - Shape mismatch: Python {py_val.shape} vs MATLAB {mat_val.shape}")
                failed_fields.append(field)
                continue

        # Compute relative and absolute errors
        diff = py_val - mat_val
        if diff.size == 0:
            # Both arrays are empty - this is actually a match
            if py_val.shape == mat_val.shape:
                print(f"PASS: {field} - Both arrays are empty with shape {py_val.shape}")
                continue
            else:
                print(f"FAIL: {field} - Shape incompatibility: Python {py_val.shape} vs MATLAB {mat_val.shape}")
                failed_fields.append(field)
                continue
        abs_error = np.max(np.abs(diff))
        rel_error = np.max(np.abs(diff) / (np.abs(py_val) + 1e-15))
        max_error = max(max_error, max(abs_error, rel_error))

        # Compute correlation
        py_flat = py_val.flatten()
        mat_flat = mat_val.flatten()

        # Remove any NaN or inf values for correlation calculation
        valid_mask = np.isfinite(py_flat) & np.isfinite(mat_flat)
        if np.sum(valid_mask) > 1:  # Need at least 2 valid points for correlation
            correlation = np.corrcoef(py_flat[valid_mask], mat_flat[valid_mask])[0, 1]
            # Handle case where correlation might be NaN (e.g., constant values)
            if np.isnan(correlation):
                # If both arrays are constant and equal, correlation should be 1
                if np.allclose(py_flat[valid_mask], mat_flat[valid_mask], atol=tolerance):
                    correlation = 1.0
                else:
                    correlation = 0.0
        else:
            correlation = 0.0

        # Check correlation threshold (main criterion for pass/fail)
        correlation_pass = correlation >= min_correlation

        # For scalar values and integer arrays, check for exact/near-exact equality
        if py_val.size == 1:
            py_scalar = py_val.item()
            mat_scalar = mat_val.item()

            if abs_error <= tolerance:
                print(f"PASS: {field} - Scalar value: {py_scalar:.8f} (diff: {abs_error:.8f})")
            else:
                print(f"FAIL: {field} - Python: {py_scalar:.8f}, MATLAB: {mat_scalar:.8f} (diff: {abs_error:.8f})")
                failed_fields.append(field)
        else:
            # Array comparisons - use correlation for pass/fail
            if correlation_pass:
                print(f"PASS: {field} - Max abs err: {abs_error:.8f}, Max rel err: {rel_error:.8f}, Corr: {correlation:.8f}")
            else:
                print(f"FAIL: {field} - Max abs err: {abs_error:.8f}, Max rel err: {rel_error:.8f}, Corr: {correlation:.8f} (CORRELATION)")
                correlation_failed_fields.append(field)
                failed_fields.append(field)
    else:
        missing_py = field not in python_results or python_results[field] is None
        missing_mat = field not in matlab_results
        print(f"SKIP: {field} - Missing in {'Python' if missing_py else 'MATLAB'}")

print("")
print("=" * 60)
if len(failed_fields) == 0:
    print(f"✓ ALL TESTS PASSED FOR TEST_NAME_PLACEHOLDER")
    print(f"  Python and MATLAB implementations are equivalent")
    print(f"  All fields passed correlation test (≥ {min_correlation})")
    print("=" * 60)
    exit_code = 0
else:
    print(f"✗ {len(failed_fields)} TESTS FAILED FOR TEST_NAME_PLACEHOLDER")
    print(f"  Failed fields: {failed_fields}")
    if len(correlation_failed_fields) > 0:
        print(f"  Fields failing correlation test: {correlation_failed_fields}")
    print(f"  Maximum error encountered: {max_error:.8f}")
    print("")
    print("IMPORTANT: MATLAB is the ground truth implementation.")
    print("These failures indicate the Python implementation needs to be")
    print("modified to match the MATLAB behavior, not vice versa.")
    print("=" * 60)
    exit_code = 1

# Save detailed comparison summary
summary = {
    'test_name': 'TEST_NAME_PLACEHOLDER',
    'failed_fields': failed_fields,
    'correlation_failed_fields': correlation_failed_fields,
    'max_error': max_error,
    'tolerance': tolerance,
    'min_correlation': min_correlation,
    'all_passed': len(failed_fields) == 0
}

np.save('TEST_DATA_DIR_PLACEHOLDER/TEST_NAME_PLACEHOLDER_comparison_summary.npy', summary)
sys.exit(exit_code)
EOFPYTHON

    # Replace placeholders
    sed "s|TEST_DATA_DIR_PLACEHOLDER|$TEST_DATA_DIR|g; s|TEST_NAME_PLACEHOLDER|$test_name|g; s|TOLERANCE_PLACEHOLDER|$TOLERANCE|g; s|MIN_CORRELATION_PLACEHOLDER|$MIN_CORRELATION|g" \
        "$TEST_DATA_DIR/compare_${test_name}.py" > "$TEST_DATA_DIR/compare_${test_name}_tmp.py"
    mv "$TEST_DATA_DIR/compare_${test_name}_tmp.py" "$TEST_DATA_DIR/compare_${test_name}.py"

    $PYTHON_CMD "$TEST_DATA_DIR/compare_${test_name}.py"
}

# Test configurations
echo "Starting PSN equivalence tests..."
echo ""

# Test results storage
test_results=()

# Test 1: Signal basis with global threshold using prediction criterion
if should_run_test 1; then
    echo "=== Test 1: Signal basis, global threshold, prediction ==="
    if run_psn_equivalence_test "test1_signal_global_pred" 20 50 3 "signal" "prediction" "global"; then
        test_results+=("PASSED")
    else
        test_results+=("FAILED")
    fi
    echo ""
fi

# Test 2: Signal basis with hybrid threshold using prediction criterion
if should_run_test 2; then
    echo "=== Test 2: Signal basis, hybrid threshold, prediction ==="
    if run_psn_equivalence_test "test2_signal_hybrid_pred" 20 50 3 "signal" "prediction" "hybrid"; then
        test_results+=("PASSED")
    else
        test_results+=("FAILED")
    fi
    echo ""
fi

# Test 3: Signal basis with unit threshold using prediction criterion
if should_run_test 3; then
    echo "=== Test 3: Signal basis, unit threshold, prediction ==="
    if run_psn_equivalence_test "test3_signal_unit_pred" 15 40 3 "signal" "prediction" "unit"; then
        test_results+=("PASSED")
    else
        test_results+=("FAILED")
    fi
    echo ""
fi

# Test 4: Signal basis with global threshold using variance criterion
if should_run_test 4; then
    echo "=== Test 4: Signal basis, global threshold, variance ==="
    if run_psn_equivalence_test "test4_signal_global_var" 20 50 3 "signal" "variance" "global" 0.95; then
        test_results+=("PASSED")
    else
        test_results+=("FAILED")
    fi
    echo ""
fi

# Test 5: Difference basis with global threshold
if should_run_test 5; then
    echo "=== Test 5: Difference basis, global threshold ==="
    if run_psn_equivalence_test "test5_diff_global" 15 40 3 "difference" "prediction" "global"; then
        test_results+=("PASSED")
    else
        test_results+=("FAILED")
    fi
    echo ""
fi

# Test 6: Difference basis with hybrid threshold
if should_run_test 6; then
    echo "=== Test 6: Difference basis, hybrid threshold ==="
    if run_psn_equivalence_test "test6_diff_hybrid" 15 40 3 "difference" "prediction" "hybrid"; then
        test_results+=("PASSED")
    else
        test_results+=("FAILED")
    fi
    echo ""
fi

# Test 7: PCA basis
if should_run_test 7; then
    echo "=== Test 7: PCA basis ==="
    # Use fewer voxels to avoid tie-breaking issues
    if run_psn_equivalence_test "test7_pca_basis" 10 40 5 "pca" "prediction" "global"; then
        test_results+=("PASSED")
    else
        test_results+=("FAILED")
    fi
    echo ""
fi

# Test 8: Random basis (shared between Python and MATLAB)
if should_run_test 8; then
    echo "=== Test 8: Random basis ==="
    # Generate shared random basis for consistent comparison
    if [ ! -f "$TEST_DATA_DIR/shared_random_basis.npy" ]; then
        echo "Generating shared random basis..."
        cat > "$TEST_DATA_DIR/generate_shared_random_basis.py" << EOFPYTHON
import numpy as np
import scipy.io

# Generate deterministic random basis using QR decomposition
# This will be shared between Python and MATLAB implementations

# Set deterministic seed
np.random.seed(123)

# Generate random matrix and orthogonalize
nvox = 15
random_matrix = np.random.randn(nvox, nvox)
Q, R = np.linalg.qr(random_matrix)

# Make sure we have a proper orthonormal basis
assert np.allclose(Q @ Q.T, np.eye(nvox), atol=1e-12), "Basis is not orthonormal"

print(f"Generated shared random basis with shape: {Q.shape}")
print(f"Orthogonality check: max(|Q*Q^T - I|) = {np.max(np.abs(Q @ Q.T - np.eye(nvox))):.2e}")

# Save for both Python and MATLAB
np.save('$TEST_DATA_DIR/shared_random_basis.npy', Q)
scipy.io.savemat('$TEST_DATA_DIR/shared_random_basis.mat', {'shared_basis': Q})

print("Shared random basis saved successfully")
EOFPYTHON
        $PYTHON_CMD "$TEST_DATA_DIR/generate_shared_random_basis.py"
    fi
    if run_psn_equivalence_test "test8_random_basis" 15 40 3 "shared_random_basis" "prediction" "global"; then
        test_results+=("PASSED")
    else
        test_results+=("FAILED")
    fi
    echo ""
fi

# Test 9: Small dataset edge case
if should_run_test 9; then
    echo "=== Test 9: Small dataset edge case ==="
    if run_psn_equivalence_test "test9_small_data" 5 10 2 "signal" "prediction" "global"; then
        test_results+=("PASSED")
    else
        test_results+=("FAILED")
    fi
    echo ""
fi

# Test 10: Variance eigenvalues criterion
if should_run_test 10; then
    echo "=== Test 10: Variance eigenvalues criterion ==="
    if run_psn_equivalence_test "test10_var_eigenvalues" 15 30 4 "signal" "variance_eigenvalues" "global" 0.95; then
        test_results+=("PASSED")
    else
        test_results+=("FAILED")
    fi
    echo ""
fi

echo ""
echo "=========================================="
echo "FINAL SUMMARY"
echo "=========================================="

test_names=(
    "Signal/global/prediction"
    "Signal/hybrid/prediction"
    "Signal/unit/prediction"
    "Signal/global/variance"
    "Difference/global"
    "Difference/hybrid"
    "PCA basis"
    "Random basis"
    "Small dataset"
    "Variance eigenvalues"
)

# Print individual test results
total_tests=${#test_results[@]}
passed_tests=0

for i in "${!test_results[@]}"; do
    result="${test_results[i]}"
    test_name="${test_names[i]}"

    if [ "$result" = "PASSED" ]; then
        echo "✓ Test $((i+1)): $test_name - PASSED"
        ((passed_tests++))
    else
        echo "✗ Test $((i+1)): $test_name - FAILED"
    fi
done

echo ""
echo "Overall Results: $passed_tests/$total_tests tests passed"

if [ $passed_tests -eq $total_tests ]; then
    echo ""
    echo "🎉 ALL PSN EQUIVALENCE TESTS PASSED!"
    echo "Python and MATLAB implementations are numerically equivalent"
    echo "across all tested parameter combinations and data configurations."
    final_exit_code=0
else
    failed_tests=$((total_tests - passed_tests))
    echo ""
    echo "❌ $failed_tests/$total_tests tests failed."
    echo ""
    echo "IMPORTANT: MATLAB is the ground truth implementation."
    echo "Any failures indicate the Python implementation needs to be"
    echo "modified to match MATLAB behavior, not vice versa."
    final_exit_code=1
fi

echo ""
echo "Test data saved in: $TEST_DATA_DIR"
echo "You can inspect individual results and comparison summaries there."

echo ""
echo "PSN equivalence testing complete!"

exit $final_exit_code
